# Numpy基础

In [11]:
# list转化为矩阵
import numpy as np
list = [[1,2,3],[2,3,4]]
array = np.array(list)
print(array)

[[1 2 3]
 [2 3 4]]


In [12]:
print (list)

[[1, 2, 3], [2, 3, 4]]


In [13]:
#几种属性
print("the dim:",array.ndim)
print("the shape:",array.shape)
print("the size:",array.size)

the dim: 2
the shape: (2, 3)
the size: 6


## NumPy 之 创建array
### 关键字
* array
* dtype
* zeros
* ones
* empty
* arrange
* linspace

In [14]:
#创建数组
a = np.array([2,23,4]) #list 1d
list1 = [2,23,4]  #后面常用
print(a)

[ 2 23  4]


In [15]:
#指定数据dtype
a = np.array(list,dtype=np.int)
print(a.dtype)

int32


In [16]:
a = np.array(list,dtype=np.int64)
print(a.dtype)

int64


In [17]:
a = np.array(list,dtype=np.float)
print(a.dtype)

float64


In [18]:
a = np.array(list,dtype=np.float32)
print(a.dtype)

float32


In [19]:
#创建特定数据

In [20]:
#创建全零数组
a = np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
#创建全1数组
a = np.ones((3,4),dtype=np.int)

In [22]:
# 创建全空数组，其实每一个都只是接近0
a = np.empty((3,4),dtype = np.float)
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


np.empty(shape,dtype=float,order='C')  
parameters:  
**shape:**int or tuple of int;e.g.,(2,3) or 2  
**dtype:**data-type, optional; e.g., np.int8 . Defualt is np.float64  
**order:** {'C','F'},optional, dafault: 'C'  
return:  
out: ndarray

In [23]:
#创建连续数组arange()
a=np.arange(10,20,2) #10-19，2为步长
print(a)

[10 12 14 16 18]


In [24]:
#改变数组的形状reshape
a=np.arange(12).reshape((3,4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [25]:
#用linspace创建线段型数据
a=np.linspace(1,10,20)#起点1，终点10.分割成20个数据
print(a)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


## NumPy 基础运算1
* 加减乘乘方
* 数学函数比如sin()
* bool运算
* 矩阵乘法 .dot
* sum(),min(),max()

### 针对ndim==1

In [26]:
import numpy as np
a=np.array([10,20,30,40])
b=np.arange(4) #[0,1,2,3]

In [27]:
# 乘与乘方 
print("a*b=",a*b)
c=a**b
print("a**b=",c)

a*b= [  0  20  60 120]
a**b= [    1    20   900 64000]


In [28]:
# sin()等函数，对每一个元素进行运算
print("10*np.sin(a)=",10*np.sin(a))

10*np.sin(a)= [-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [29]:
#bool运算
print("are everyone in b less than 3? ",b<3)

are everyone in b less than 3?  [ True  True  True False]


-----

### ndim == 2

In [30]:
a = np.array([[1,1],[0,1]])
b = np.arange(4).reshape((2,2))
print("a=",a)
print('b=',b)

a= [[1 1]
 [0 1]]
b= [[0 1]
 [2 3]]


In [31]:
#矩阵乘法运算 .dot ---两种形式
print('np.dot(a,b)=',np.dot(a,b))
print('a.dot(b)=',a.dot(b))

np.dot(a,b)= [[2 4]
 [2 3]]
a.dot(b)= [[2 4]
 [2 3]]


In [32]:
# sum()/min()/max()
print('np.sum(b)=',np.sum(b))
print('np.min(b)=',np.min(b))
print('np.max(b)=',np.max(b))

np.sum(b)= 6
np.min(b)= 0
np.max(b)= 3


In [33]:
# 求某一行的sun/min/max..加标记axis=0/1..0为列
print('b=',b)
print('np.sum(b,axis=1)=',np.sum(b,axis=1))
print('np.min(b,axis=1)=',np.min(b,axis=1))
print('np.max(b,axis=1)=',np.max(b,axis=1))

b= [[0 1]
 [2 3]]
np.sum(b,axis=1)= [1 5]
np.min(b,axis=1)= [0 2]
np.max(b,axis=1)= [1 3]


## Numpy基础运算（2）

* 最大最小元素的索引
* 均值/中位数/累加/累差
* nonzero() #有何意义
* 排序
* 矩阵的转置
* clip (Array, Array_min,Array_max)

In [34]:
import numpy as np
A = np.arange(2,14).reshape((3,4)) 
print('A=',A)         
print('np.argmin(A)=',np.argmin(A))    # 0
print('np.argmax(A)=',A.argmax())    # 11

A= [[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
np.argmin(A)= 0
np.argmax(A)= 11


In [37]:
# 均值/中位数/累加/累差
print('A=',A)
print('A.mean()=',A.mean())
print('np.average(A)=',np.average(A))
print('np.median(A)=',np.median(A))
print('np.cumsum(A)=',np.cumsum(A)) #accumlate 累计
print('A.diff()=',A.diff())

A= [[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
A.mean()= 7.5
np.average(A)= 7.5
np.median(A)= 7.5
np.cumsum(A)= [ 2  5  9 14 20 27 35 44 54 65 77 90]


AttributeError: 'numpy.ndarray' object has no attribute 'diff'

In [38]:
# 均值/中位数/累加/累差(再来一遍)
print('A=',A)
print('A.mean()=',A.mean())
print('np.average(A)=',np.average(A))
print('np.median(A)=',np.median(A))
print('np.cumsum(A)=',np.cumsum(A)) #accumlate 累计
print('np.diff(A)=',np.diff(A))

A= [[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
A.mean()= 7.5
np.average(A)= 7.5
np.median(A)= 7.5
np.cumsum(A)= [ 2  5  9 14 20 27 35 44 54 65 77 90]
np.diff(A)= [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
# nonzero()
print('A=',A)
print('np.nonzero(A)=',np.nonzero(A))

In [ ]:
# sort()
A=np.arange(14,2,-1).reshape(3,4)
print('A=',A)
print('np.sort(A)=',np.sort(A))

In [ ]:
#转置
print('A',A)
print('A.T=',A.T)
print('np.transpose(A)=',np.transpose(A))

In [ ]:
#clip(Array,Array_min,Array_max) 将Array中比min小的换成min；比max大的换成max
print('A=',A)
print('np.clip(A,5,9)=',np.clip(A,5,9))

## Numpy 索引

* 一维索引
* 二维索引与切片
* 逐行/列打印
* flatten() #拉直

In [ ]:
# 一维索引同列表索引，故而省略
A = np.arange(15,3,-1).reshape((3,4))
print('A=',A)

In [ ]:
#2darray的索引与切片
print('A[1][1]=',A[1][1])
print('A[1,1]=',A[1,1])
print('A[1,1:4]=',A[1,1:4])

In [ ]:
#按行打印
print('A=',A)
for row in A:
    print(row)
print('按列打印如下')
for column in A.T:
    print(column)


In [ ]:
# A.flatten() 拉直以及flat迭代器
print('A=',A)
print('A.flatten()=',A.flatten())
for item in A.flat:
    print(item)

## Numpy 合并
* np.vstack() vertical stack 垂直的
* np.hstack() horizontal stack 水平的
* np.newaxis() 
* np.concatenate()

In [ ]:
# vstack()
A= np.array([1,1,1])
B= np.array([2,2,2])
C = np.vstack((A,B))  # 注意传入的参数是一个turple
print('C=',C)

In [ ]:
# hstack()
D=np.hstack((A,B))
print('np.hsatck((A,B))',D)

In [ ]:
#怎样把一个横向的数列编程纵向的？
# 先看看转置管用否
print('A=',A)
print('A.T=',A.T)
print('原因是A.shape=',A.shape,'不是(1,3)')

In [ ]:
# 变成1*3 或者 3*1
print('A[np.newaxis,:]=',A[np.newaxis,:])
print('A[np.newaxis,:].shape=',A[np.newaxis,:].shape)
print('A[:,np.newaxis]=',A[:,np.newaxis],'用到了切片')
print('A[:,np.newaxis].shape=',A[:,np.newaxis].shape)

In [ ]:
import numpy as np
A = np.array([1,1,1])[:,np.newaxis]
B = np.array([2,2,2])[:,np.newaxis]
         
C = np.vstack((A,B))   # vertical stack
D = np.hstack((A,B))   # horizontal stack

print(D)
"""
[[1 2]
[1 2]
[1 2]]
"""

print(A.shape,D.shape)
# (3,1) (3,2)

In [ ]:
# 合并大于两个 concatenate()

print('A=',A)
print('B=',B)
C= np.concatenate((A,B,B,A),axis=0)
print("np.concatenate((A,B,B,A),axis=0)",C)
print('C.shape=',C.shape)

In [ ]:
# 等分
import numpy as np
A=np.arange(12).reshape(3,4)
print('A=',A)
print('np.split(A,2,axis=1)=',np.split(A,2,axis=1)) # 1代表横向 
print('np.split(A,3,axis=0)=',np.split(A,3,axis=0)) # 0代表纵向

In [ ]:
# 不等分
print('A=',A)
print('np.array_split(A,2,axis=0)=',np.array_split(A,2,axis=0))

In [ ]:
# np.split(A,2,axis = 1)等价于np.hsplit(A,2)
print(np.split(A,2,axis = 1))

## Numpy copy & deep copy

* = 的赋值方式有关联性
* copy()方式无关联性

In [ ]:
import numpy as np
a= np.array([1,2,3,4])
b=a
c=b
d=c

In [ ]:
#改变d的值看看,a变不变呢
d[2]=100
print('d=',d)
print('a=',a)

In [ ]:
# 换成copy()试试
import numpy as np
a= np.array([1,2,3,4])
b=np.copy(a)

In [ ]:
# 改变a的值，b变否？
a[0]=100
print('b=',b)